run:
  deadline: 10m
  skip-dirs:
    - temp
  skip-files:
    - ".*_gen.go$"
  tests: false
  sort-results: true
linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - gochecknoglobals
    - nlreturn
    - scopelint
    - maligned
    - interfacer
    - wrapcheck
    - golint
    - exhaustive
linters-settings:
  godox:
    keywords:
      - NOTE
      - HACK
      - TEMP
      - FIX
      - FIXME
  cyclop:
    max-complexity: 15